CREATE SCHEMA OPENAI;
USE OPENAI;

CREATE TABLE CHAT_HISTORY (
	id INT PRIMARY KEY AUTO_INCREMENT,
    dni VARCHAR(10),
    content VARCHAR(100),
    role VARCHAR(20),
    date DATETIME DEFAULT CURRENT_TIMESTAMP(6)
)